#include <linux/kernel.h>
#include <linux/board-ragentek-cfg.h>
/*=====================Data type define==================*/
typedef struct
{
	int lcd_type;
	int nMinVoltage;
	int nMaxVoltage;	
}lcd_info_type;

typedef struct
{
	unsigned projt_id;	
	lcd_info_type *lcd_info_ptr;
}lcd_info_table_type;

static unsigned rgtk_product_id;
static unsigned rgtk_lcd_id;

static unsigned rgt_cta_flag;  //add by wangtao

/*==================LCD type configuration Table=================*/
static lcd_info_type lcd_info_for_q801[] =
{
        {MIPI_QHD_LCD_DNJ_OTM9608A,0,500}, //dnj 0
        {MIPI_QHD_LCD_TRULY_OTM9608A, 800,1000}, //truly 0.9V
        {MIPI_QHD_LCD_OTM9608A,1700,1900}, //king_display 1.8V
	{MIPI_QHD_LCD_TRULY_NT35516,1400,1600}, // 1.5V
	{INVALID_LCD_TYPE, 0, 0}
};

static lcd_info_type lcd_info_for_q802[] =
{
	{RGB_DJN_LCD_HX8369, 0, 200},//0V
        {RGB_DNJ_LCD_OTM8018B,200, 400},//0.3V
	{RGB_TRULY_LCD_HX8369,1750, 1850},//1.8V
	{RGB_AZET_LCD_NT35510,1000, 1400},
	{RGB_DNJ_LCD_OTM8018B_IPS_2,1410, 1740},
	{RGB_DNJ_LCD_OTM8018B_IPS,800, 1000},//0.9V 
        {RGB_TS_LCD_NT35512_IPS,500,700},	
	{INVALID_LCD_TYPE, 0, 0}
};

static lcd_info_type lcd_info_for_q803[] =
{
         
        {MIPI_ORISE_LCD_OTM8009A,800,999},  //0.9V
        {MIPI_TCL_LCD_NT35510, 1000, 1400}, //1.2v
	{INVALID_LCD_TYPE, 0, 0}
};

static lcd_info_type lcd_info_for_q203[] =
{
	{MIPI_AZET_LCD_NT35510, 200, 400}, //0.4v
	{MIPI_TRULY_LCD_OTM8018B, 500, 700}, //0.6v
	{MIPI_AZET_LCD_OTM8018B, 800, 1000}, //0.9v
	{MIPI_DJN_LCD_OTM8018B, 1600, 2000}, //1.8v	
	{INVALID_LCD_TYPE, 0, 0}
};

static lcd_info_type lcd_info_for_q203_nand[] =
{
	{MIPI_AZET_LCD_NT35510, 200, 400}, //0.4v
	{MIPI_DJN_LCD_OTM8018B, 1600, 2000}, //1.8v	
	{INVALID_LCD_TYPE, 0, 0}
};

static lcd_info_type lcd_info_for_dc205[] =
{
	{MIPI_AZET_LCD_NT35510, 200, 400}, //0.4v
	{MIPI_TRULY_LCD_OTM8018B, 500, 700}, //0.6v
	{MIPI_AZET_LCD_OTM8018B, 800, 1000}, //0.9v
	{MIPI_DJN_LCD_OTM8018B, 1600, 2000}, //1.8v	
	{INVALID_LCD_TYPE, 0, 0}
};


lcd_info_table_type lcd_info_table[] = {
	{RGTK_PRODUCT_Q801, lcd_info_for_q801},
	{RGTK_PRODUCT_Q802, lcd_info_for_q802},
	{RGTK_PRODUCT_Q803, lcd_info_for_q803},	
	{RGTK_PRODUCT_Q203, lcd_info_for_q203},	
	{RGTK_PRODUCT_Q203_NAND, lcd_info_for_q203_nand},	
	{RGTK_PRODUCT_DC205, lcd_info_for_dc205},	
	{RGTK_PRODUCT_INVALID,   NULL},
};
/*================Endof LCD type configuration Table===============*/

int lcd_mv_to_id(unsigned lcd_id_mv)
{
	int i=0;
	int ret = INVALID_LCD_TYPE;
	lcd_info_type *lcd_info = NULL;
		
	for(i=0; RGTK_PRODUCT_INVALID != lcd_info_table[i].projt_id; i++){
		if(lcd_info_table[i].projt_id == rgtk_product_id){
			lcd_info = lcd_info_table[i].lcd_info_ptr;
		}
	}

	if(NULL != lcd_info){
		for(i = 0; INVALID_LCD_TYPE != lcd_info[i].lcd_type; i++){
			if(lcd_id_mv >= lcd_info[i].nMinVoltage
				&& lcd_id_mv <= lcd_info[i].nMaxVoltage) {
				ret = lcd_info[i].lcd_type;
printk("luke: Detected lcd_id voltage is: %u mv\n",lcd_id_mv);		
			}
		}
	}
	if(rgtk_product_id == RGTK_PRODUCT_Q203 \
		||rgtk_product_id == RGTK_PRODUCT_DC205)//add by hxh for :cannot do rf test when no display driver was registered! 2012.11.14
	{
            if(ret == INVALID_LCD_TYPE)
            ret = RGB_DJN_LCD_HX8369;
	}//end 
	pr_info("lcd type: 0x%x\n", ret);

	return ret;
} 

void set_rgtk_product(unsigned product)
{
	rgtk_product_id = product;
}

unsigned get_rgtk_product(void)
{
	return rgtk_product_id;
}
EXPORT_SYMBOL_GPL(get_rgtk_product);

bool is_rgtk_product(unsigned product)
{
	return (rgtk_product_id ==product)? 1:0;
}
EXPORT_SYMBOL_GPL(is_rgtk_product);

void set_rgtk_lcd_id(int lcd_id)
{
	rgtk_lcd_id = lcd_id;
}

unsigned get_rgtk_lcd_id(void)
{
	return rgtk_lcd_id;
}
EXPORT_SYMBOL_GPL(get_rgtk_lcd_id);

unsigned is_rgtk_lcd_id(int lcd_id)
{
	return (rgtk_lcd_id == lcd_id)?1:0;
}
EXPORT_SYMBOL_GPL(is_rgtk_lcd_id);

void set_cta_flag(unsigned flag)
{
	rgt_cta_flag = flag;
}

unsigned get_cta_flag(void)
{
	return rgt_cta_flag;
}
EXPORT_SYMBOL_GPL(get_cta_flag);
/*=====================Gpio configuration=======================*/

unsigned int gpio_num[GPIO_TOTAL_NUM];
unsigned int gpio_cfg[GPIO_TOTAL_NUM];
 
void q801_setup_gpio(void)
{
	gpio_num[GPIO_OVP_FLAG_INDEX]		= INVALID_GPIO; /*GPIO_OVP_FLAG*/
	gpio_num[GPIO_BT_SYS_REST_EN_INDEX]	= 16; /*GPIO_BT_SYS_REST_EN*/
        /*lilonghui add it for the camera flashlight 2012-2-29 */
	gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX]= 94; 
	gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX]	= 49; /*TRUE CAMERA FLASH LIGHT ENABLE*/
        /* end */
	gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX]	= INVALID_GPIO, /*FAKE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_ID_INDEX]		= 109; /*CAMERA ID*/
	gpio_num[GPIO_CAM_DRIVER_PWDN]		= 30;	
	gpio_num[GPIO_CAM_FRONT_PWDN_INDEX]	= 18; /*GPIO_CAM_FRONT_PWDN*/
	gpio_num[GPIO_CAM_FRONT_RESET_INDEX] 	= 29; /*GPIO_CAM_FRONT_RESET_INDEX*/
	gpio_num[GPIO_ALS_INT_INDEX]		= 17; /*GPIO_ALS_INT_INDEX*/
	gpio_num[GPIO_CAM_BACK_PWDN_INDEX]	= 122; 
	gpio_num[GPIO_CAM_BACK_RESET_INDEX]	= 123; 
	gpio_num[GPIO_FM_RDS_INT_INDEX]		= 83;  /*GPIO_FM_RDS_INT*/
	gpio_num[GPIO_SDC1_HW_DET_INDEX] 	= 42;  /*GPIO_SDC1_HW_DET*/
	gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX]	= 26; 
	gpio_num[GPIO_TOUCH_PANEL_INT_INDEX] 	= 48;  
	gpio_num[GPIO_COMPASS_DRDY_INDEX]	= 27;
	gpio_num[GPIO_GYRO_INT_N_INDEX] 	= INVALID_GPIO; 
	gpio_num[GPIO_ACC_INT_INDEX]		= 28; 
	gpio_num[GPIO_EXT_2V85_EN_INDEX] 	= 35;	
	gpio_num[GPIO_LCD_RESET_INDEX]		= 85;	
	gpio_num[GPIO_LCD_LED_EN_INDEX]		= 96;	
	gpio_num[GPIO_KEYPAD_LED_EN_INDEX]	= INVALID_GPIO;	
	gpio_num[KYPD_DRV0_INDEX]		= 31;	/*KYPD_DRV0*/
	gpio_num[KYPD_DRV1_INDEX]		= 32;	/*KYPD_DRV0*/
	gpio_num[KEYSENSE_N0_INDEX]		= 36;	/*KEYSENSE_N0*/
	gpio_num[KEYSENSE_N1_INDEX]		= 37;	/*KEYSENSE_N0*/

	gpio_cfg[GPIO_OVP_FLAG_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_OVP_FLAG_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[GPIO_BT_SYS_REST_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_BT_SYS_REST_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*lilonghui add it for the camera flash light 2012-6-29*/
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWM_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*end*/
	gpio_cfg[GPIO_CAM_FAKE_FLASH_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_ID_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_ID_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_DRIVER_PWDN] = 
		GPIO_CFG(gpio_num[GPIO_CAM_DRIVER_PWDN], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_CAM_FRONT_PWDN_INDEX] =
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FRONT_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ALS_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ALS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_PWDN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_FM_RDS_INT_INDEX]	=  
		GPIO_CFG(gpio_num[GPIO_FM_RDS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_SDC1_HW_DET_INDEX] = //modify by fangxing from PULL_UP to NO_PULL
		GPIO_CFG(gpio_num[GPIO_SDC1_HW_DET_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_COMPASS_DRDY_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_COMPASS_DRDY_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_GYRO_INT_N_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_GYRO_INT_N_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ACC_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ACC_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_EXT_2V85_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_EXT_2V85_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_LCD_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_RESET_INDEX], 0,  GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_LCD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_KEYPAD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_KEYPAD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV0_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV0_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV1_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV1_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N0_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N0_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N1_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N1_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
}

void q802_setup_gpio(void)
{
	gpio_num[GPIO_OVP_FLAG_INDEX]		= INVALID_GPIO; /*GPIO_OVP_FLAG*/
	gpio_num[GPIO_BT_SYS_REST_EN_INDEX]	= 16; /*GPIO_BT_SYS_REST_EN*/                                         
	gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX]	= INVALID_GPIO; /*TRUE CAMERA FLASH LIGHT ENABLE*/                    
	gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX]	= 94, /*FAKE CAMERA FLASH LIGHT ENABLE*/                              
	gpio_num[GPIO_CAM_ID_INDEX]		= 109; /*CAMERA ID*/                                                  
	gpio_num[GPIO_CAM_DRIVER_PWDN]		= 30;	                                                              
	gpio_num[GPIO_CAM_FRONT_PWDN_INDEX]	= 18; /*GPIO_CAM_FRONT_PWDN*/                                         
	gpio_num[GPIO_CAM_FRONT_RESET_INDEX] 	= 29; /*GPIO_CAM_FRONT_RESET_INDEX*/                                  
	gpio_num[GPIO_ALS_INT_INDEX]		= 17; /*GPIO_ALS_INT_INDEX*/                                          
	gpio_num[GPIO_CAM_BACK_PWDN_INDEX]	= 122;                                                                
	gpio_num[GPIO_CAM_BACK_RESET_INDEX]	= 123;                                                                
	gpio_num[GPIO_FM_RDS_INT_INDEX]		= 83;  /*GPIO_FM_RDS_INT*/                                            
	gpio_num[GPIO_SDC1_HW_DET_INDEX] 	= 42;  /*GPIO_SDC1_HW_DET*/                                           
	gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX]	= 26;                                                                 
	gpio_num[GPIO_TOUCH_PANEL_INT_INDEX] 	= 48;                                                                 
	gpio_num[GPIO_COMPASS_DRDY_INDEX]	= 27;                                                                 
	gpio_num[GPIO_GYRO_INT_N_INDEX] 	= INVALID_GPIO;                                                       
	gpio_num[GPIO_ACC_INT_INDEX]		= 28;                                                                 
	gpio_num[GPIO_EXT_2V85_EN_INDEX] 	= 35;	                                                              
	gpio_num[GPIO_LCD_RESET_INDEX]		= 85;	/* GYRO_INT_N */                                              
	gpio_num[GPIO_LCD_LED_EN_INDEX]		= INVALID_GPIO;	                                                      
	gpio_num[GPIO_KEYPAD_LED_EN_INDEX]	= INVALID_GPIO;	                                                      
	gpio_num[KYPD_DRV0_INDEX]		= 31;	/*KYPD_DRV0*/
	gpio_num[KYPD_DRV1_INDEX]		= INVALID_GPIO;	/*KYPD_DRV0*/
	gpio_num[KEYSENSE_N0_INDEX]		= 36;	/*KEYSENSE_N0*/
	gpio_num[KEYSENSE_N1_INDEX]		= 37;	/*KEYSENSE_N0*/

	gpio_cfg[GPIO_OVP_FLAG_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_OVP_FLAG_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[GPIO_BT_SYS_REST_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_BT_SYS_REST_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWM_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FAKE_FLASH_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_ID_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_ID_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_DRIVER_PWDN] = 
		GPIO_CFG(gpio_num[GPIO_CAM_DRIVER_PWDN], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_CAM_FRONT_PWDN_INDEX] =
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FRONT_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ALS_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ALS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_PWDN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_FM_RDS_INT_INDEX]	=  
		GPIO_CFG(gpio_num[GPIO_FM_RDS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_SDC1_HW_DET_INDEX] = //modify by fangxing from PULL_UP to NO_PULL
		GPIO_CFG(gpio_num[GPIO_SDC1_HW_DET_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_COMPASS_DRDY_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_COMPASS_DRDY_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_GYRO_INT_N_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_GYRO_INT_N_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ACC_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ACC_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_EXT_2V85_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_EXT_2V85_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_LCD_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_LCD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_KEYPAD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_KEYPAD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV0_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV0_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV1_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV1_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N0_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N0_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N1_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N1_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
}


void q803_setup_gpio(void)
{
	gpio_num[GPIO_OVP_FLAG_INDEX]		= 41; /*GPIO_OVP_FLAG*/
	gpio_num[GPIO_BT_SYS_REST_EN_INDEX]	= 16; /*GPIO_BT_SYS_REST_EN*/
	gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX]	= 94; /*TRUE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX]	= 34;
	gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX]	= 13, /*FAKE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_ID_INDEX]		= 109; /*CAMERA ID*/
	gpio_num[GPIO_CAM_DRIVER_PWDN]		= 30;	
	gpio_num[GPIO_CAM_FRONT_PWDN_INDEX]	= 18; /*GPIO_CAM_FRONT_PWDN*/
	gpio_num[GPIO_CAM_FRONT_RESET_INDEX] 	= 29; /*GPIO_CAM_FRONT_RESET_INDEX*/
	gpio_num[GPIO_ALS_INT_INDEX]		= 17; /*GPIO_ALS_INT_INDEX*/
	gpio_num[GPIO_CAM_BACK_PWDN_INDEX]	= 122; 
	gpio_num[GPIO_CAM_BACK_RESET_INDEX]	= 123; 
	gpio_num[GPIO_FM_RDS_INT_INDEX]		= 83;  /*GPIO_FM_RDS_INT*/
	gpio_num[GPIO_SDC1_HW_DET_INDEX] 	= 40;  /*GPIO_SDC1_HW_DET*/
	gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX]	= 26; 
	gpio_num[GPIO_TOUCH_PANEL_INT_INDEX] 	= 48;  
	gpio_num[GPIO_COMPASS_DRDY_INDEX]	= 27;		//sym modify
	gpio_num[GPIO_GYRO_INT_N_INDEX] 	= INVALID_GPIO;   //sym modify
	gpio_num[GPIO_ACC_INT_INDEX]		= 28; 
	gpio_num[GPIO_EXT_2V85_EN_INDEX] 	= 35;	
	gpio_num[GPIO_LCD_RESET_INDEX]		= 85;	/* GYRO_INT_N */
	gpio_num[GPIO_LCD_LED_EN_INDEX]		= 96;	/* ACC_INT(LIS3DH) */
	gpio_num[GPIO_RED_LED_EN_INDEX]		= 107;	/* LTR502_INT_GPIO */
	gpio_num[KYPD_DRV0_INDEX]		= 31;	/*KYPD_DRV0*/
	gpio_num[KYPD_DRV1_INDEX]		= 32;	/*KYPD_DRV0*/
	gpio_num[KEYSENSE_N0_INDEX]		= 36;	/*KEYSENSE_N0*/
	gpio_num[KEYSENSE_N1_INDEX]		= 37;	/*KEYSENSE_N0*/

	gpio_cfg[GPIO_OVP_FLAG_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_OVP_FLAG_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[GPIO_BT_SYS_REST_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_BT_SYS_REST_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*lilonghui add it for the camera flash light 2012-6-29*/
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWM_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*end*/
	gpio_cfg[GPIO_CAM_FAKE_FLASH_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_ID_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_ID_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_DRIVER_PWDN] = 
		GPIO_CFG(gpio_num[GPIO_CAM_DRIVER_PWDN], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_CAM_FRONT_PWDN_INDEX] =
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FRONT_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ALS_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ALS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_PWDN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_FM_RDS_INT_INDEX]	=  
		GPIO_CFG(gpio_num[GPIO_FM_RDS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_SDC1_HW_DET_INDEX] = //modify by fangxing from PULL_UP to NO_PULL
		GPIO_CFG(gpio_num[GPIO_SDC1_HW_DET_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_COMPASS_DRDY_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_COMPASS_DRDY_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_GYRO_INT_N_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_GYRO_INT_N_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ACC_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ACC_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_EXT_2V85_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_EXT_2V85_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_LCD_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_LCD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_KEYPAD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_RED_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV0_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV0_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV1_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV1_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N0_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N0_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N1_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N1_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
}

void q203_setup_gpio(void)
{
	gpio_num[GPIO_OVP_FLAG_INDEX]		= INVALID_GPIO; /*GPIO_OVP_FLAG*/
	gpio_num[GPIO_BT_SYS_REST_EN_INDEX]	= 16; /*GPIO_BT_SYS_REST_EN*/
	gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX]	= INVALID_GPIO; /*TRUE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX]	= INVALID_GPIO;
	gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX]	= 34, /*FAKE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_ID_INDEX]		= INVALID_GPIO; /*CAMERA ID*/
	gpio_num[GPIO_CAM_DRIVER_PWDN]		= 30;	
	gpio_num[GPIO_CAM_FRONT_PWDN_INDEX]	= 18; /*GPIO_CAM_FRONT_PWDN*/
	gpio_num[GPIO_CAM_FRONT_RESET_INDEX] 	= 29; /*GPIO_CAM_FRONT_RESET_INDEX*/
	gpio_num[GPIO_ALS_INT_INDEX]		= 17; /*GPIO_ALS_INT_INDEX*/
	gpio_num[GPIO_CAM_BACK_PWDN_INDEX]	= 122; 
	gpio_num[GPIO_CAM_BACK_RESET_INDEX]	= 123; 
	gpio_num[GPIO_FM_RDS_INT_INDEX]		= 83;  /*GPIO_FM_RDS_INT*/
	gpio_num[GPIO_SDC1_HW_DET_INDEX] 	= INVALID_GPIO;  /*GPIO_SDC1_HW_DET*/
	gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX]	= 26; 
	gpio_num[GPIO_TOUCH_PANEL_INT_INDEX] 	= 48;  
	gpio_num[GPIO_COMPASS_DRDY_INDEX]	= 27;		//sym modify
	gpio_num[GPIO_GYRO_INT_N_INDEX] 	= INVALID_GPIO;   //sym modify
	gpio_num[GPIO_ACC_INT_INDEX]		= 28; 
	gpio_num[GPIO_EXT_2V85_EN_INDEX] 	= 35;	
	gpio_num[GPIO_LCD_RESET_INDEX]		= 85;	/* GYRO_INT_N */
	gpio_num[GPIO_LCD_LED_EN_INDEX]		= 96;	/* ACC_INT(LIS3DH) */
	gpio_num[GPIO_RED_LED_EN_INDEX]		= 109;	/* LTR502_INT_GPIO */
	gpio_num[KYPD_DRV0_INDEX]		= 31;	/*KYPD_DRV0*/
	gpio_num[KYPD_DRV1_INDEX]		= 32;	/*KYPD_DRV0*/
	gpio_num[KEYSENSE_N0_INDEX]		= 36;	/*KEYSENSE_N0*/
	gpio_num[KEYSENSE_N1_INDEX]		= 37;	/*KEYSENSE_N0*/

	gpio_cfg[GPIO_OVP_FLAG_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_OVP_FLAG_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[GPIO_BT_SYS_REST_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_BT_SYS_REST_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*lilonghui add it for the camera flash light 2012-6-29*/
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWM_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*end*/
	gpio_cfg[GPIO_CAM_FAKE_FLASH_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_ID_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_ID_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_DRIVER_PWDN] = 
		GPIO_CFG(gpio_num[GPIO_CAM_DRIVER_PWDN], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_CAM_FRONT_PWDN_INDEX] =
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FRONT_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ALS_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ALS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_PWDN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_FM_RDS_INT_INDEX]	=  
		GPIO_CFG(gpio_num[GPIO_FM_RDS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_SDC1_HW_DET_INDEX] = //modify by fangxing from PULL_UP to NO_PULL
		GPIO_CFG(gpio_num[GPIO_SDC1_HW_DET_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_COMPASS_DRDY_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_COMPASS_DRDY_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_GYRO_INT_N_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_GYRO_INT_N_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ACC_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ACC_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_EXT_2V85_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_EXT_2V85_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_LCD_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_LCD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_KEYPAD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_RED_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV0_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV0_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV1_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV1_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N0_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N0_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N1_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N1_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
}

void q203_nand_setup_gpio(void)
{
	gpio_num[GPIO_OVP_FLAG_INDEX]		= INVALID_GPIO; /*GPIO_OVP_FLAG*/
	gpio_num[GPIO_BT_SYS_REST_EN_INDEX]	= 85; /*GPIO_BT_SYS_REST_EN*/      
	gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX]	= INVALID_GPIO; /*TRUE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX]	= 96, /*FAKE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_ID_INDEX]		= INVALID_GPIO; /*CAMERA ID*/
	gpio_num[GPIO_CAM_DRIVER_PWDN]		= INVALID_GPIO;	
	gpio_num[GPIO_CAM_FRONT_PWDN_INDEX]	= 91; /*GPIO_CAM_FRONT_PWDN*/
	gpio_num[GPIO_CAM_FRONT_RESET_INDEX] 	= 29; /*GPIO_CAM_FRONT_RESET_INDEX*/
	gpio_num[GPIO_ALS_INT_INDEX]		= 17; /*GPIO_ALS_INT_INDEX*/
	gpio_num[GPIO_CAM_BACK_PWDN_INDEX]	= 93; 
	gpio_num[GPIO_CAM_BACK_RESET_INDEX]	= 23; 
	gpio_num[GPIO_FM_RDS_INT_INDEX]		= 83;  /*GPIO_FM_RDS_INT*/
	gpio_num[GPIO_SDC1_HW_DET_INDEX] 	= INVALID_GPIO;  /*GPIO_SDC1_HW_DET*/
	gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX]	= 26; 
	gpio_num[GPIO_TOUCH_PANEL_INT_INDEX] 	= 48;  
	gpio_num[GPIO_COMPASS_DRDY_INDEX]	= INVALID_GPIO;
	gpio_num[GPIO_GYRO_INT_N_INDEX] 	= INVALID_GPIO; 
	gpio_num[GPIO_ACC_INT_INDEX]		= 28; 
	gpio_num[GPIO_EXT_2V85_EN_INDEX] 	= INVALID_GPIO;	
	gpio_num[GPIO_LCD_RESET_INDEX]		= 90;	
	gpio_num[GPIO_LCD_LED_EN_INDEX]		= INVALID_GPIO;	
	gpio_num[GPIO_KEYPAD_LED_EN_INDEX]	= INVALID_GPIO;	
	gpio_num[KYPD_DRV0_INDEX]		= 31;	/*KYPD_DRV0*/
	gpio_num[KYPD_DRV1_INDEX]		= INVALID_GPIO;	/*KYPD_DRV0*/
	gpio_num[KEYSENSE_N0_INDEX]		= 36;	/*KEYSENSE_N0*/
	gpio_num[KEYSENSE_N1_INDEX]		= 37;	/*KEYSENSE_N0*/

	gpio_cfg[GPIO_OVP_FLAG_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_OVP_FLAG_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[GPIO_BT_SYS_REST_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_BT_SYS_REST_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*lilonghui add it for the camera flash light 2012-6-29*/
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWM_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*end*/
	gpio_cfg[GPIO_CAM_FAKE_FLASH_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_ID_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_ID_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_DRIVER_PWDN] = 
		GPIO_CFG(gpio_num[GPIO_CAM_DRIVER_PWDN], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_CAM_FRONT_PWDN_INDEX] =
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FRONT_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ALS_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ALS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_PWDN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_FM_RDS_INT_INDEX]	=  
		GPIO_CFG(gpio_num[GPIO_FM_RDS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_SDC1_HW_DET_INDEX] = //modify by fangxing from PULL_UP to NO_PULL
		GPIO_CFG(gpio_num[GPIO_SDC1_HW_DET_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_COMPASS_DRDY_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_COMPASS_DRDY_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_GYRO_INT_N_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_GYRO_INT_N_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ACC_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ACC_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_EXT_2V85_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_EXT_2V85_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_LCD_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_LCD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_KEYPAD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_RED_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV0_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV0_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV1_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV1_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N0_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N0_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N1_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N1_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
}

void dc205_setup_gpio(void)
{
	gpio_num[GPIO_OVP_FLAG_INDEX]		= INVALID_GPIO; /*GPIO_OVP_FLAG*/
	gpio_num[GPIO_BT_SYS_REST_EN_INDEX]	= 16; /*GPIO_BT_SYS_REST_EN*/
	gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX]	= INVALID_GPIO; /*TRUE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX]	= INVALID_GPIO;
	gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX]	= 34, /*FAKE CAMERA FLASH LIGHT ENABLE*/
	gpio_num[GPIO_CAM_ID_INDEX]		= INVALID_GPIO; /*CAMERA ID*/
	gpio_num[GPIO_CAM_DRIVER_PWDN]		= 30;	
	gpio_num[GPIO_CAM_FRONT_PWDN_INDEX]	= 18; /*GPIO_CAM_FRONT_PWDN*/
	gpio_num[GPIO_CAM_FRONT_RESET_INDEX] 	= 29; /*GPIO_CAM_FRONT_RESET_INDEX*/
	gpio_num[GPIO_ALS_INT_INDEX]		= 17; /*GPIO_ALS_INT_INDEX*/
	gpio_num[GPIO_CAM_BACK_PWDN_INDEX]	= 18; 
	gpio_num[GPIO_CAM_BACK_RESET_INDEX]	= 29; 
	gpio_num[GPIO_FM_RDS_INT_INDEX]		= 83;  /*GPIO_FM_RDS_INT*/
	gpio_num[GPIO_SDC1_HW_DET_INDEX] 	= INVALID_GPIO;  /*GPIO_SDC1_HW_DET*/
	gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX]	= 26; 
	gpio_num[GPIO_TOUCH_PANEL_INT_INDEX] 	= 48;  
	gpio_num[GPIO_COMPASS_DRDY_INDEX]	= 27;		//sym modify
	gpio_num[GPIO_GYRO_INT_N_INDEX] 	= INVALID_GPIO;   //sym modify
	gpio_num[GPIO_ACC_INT_INDEX]		= 28; 
	gpio_num[GPIO_EXT_2V85_EN_INDEX] 	= 35;	
	gpio_num[GPIO_LCD_RESET_INDEX]		= 85;	/* GYRO_INT_N */
	gpio_num[GPIO_LCD_LED_EN_INDEX]		= 96;	/* ACC_INT(LIS3DH) */
	gpio_num[GPIO_RED_LED_EN_INDEX]		= INVALID_GPIO;	/* LTR502_INT_GPIO */
	gpio_num[KYPD_DRV0_INDEX]		= 31;	/*KYPD_DRV0*/
	gpio_num[KYPD_DRV1_INDEX]		= 32;	/*KYPD_DRV0*/
	gpio_num[KEYSENSE_N0_INDEX]		= 36;	/*KEYSENSE_N0*/
	gpio_num[KEYSENSE_N1_INDEX]		= 37;	/*KEYSENSE_N0*/

	gpio_cfg[GPIO_OVP_FLAG_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_OVP_FLAG_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[GPIO_BT_SYS_REST_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_BT_SYS_REST_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*lilonghui add it for the camera flash light 2012-6-29*/
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWM_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWM_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_TRUE_FLASH_PWN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_TRUE_FLASH_PWN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	/*end*/
	gpio_cfg[GPIO_CAM_FAKE_FLASH_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FAKE_FLASH_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_ID_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_ID_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_DRIVER_PWDN] = 
		GPIO_CFG(gpio_num[GPIO_CAM_DRIVER_PWDN], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_CAM_FRONT_PWDN_INDEX] =
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_FRONT_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_FRONT_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ALS_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ALS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_PWDN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_PWDN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_CAM_BACK_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_CAM_BACK_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_FM_RDS_INT_INDEX]	=  
		GPIO_CFG(gpio_num[GPIO_FM_RDS_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_SDC1_HW_DET_INDEX] = //modify by fangxing from PULL_UP to NO_PULL
		GPIO_CFG(gpio_num[GPIO_SDC1_HW_DET_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_TOUCH_PANEL_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_TOUCH_PANEL_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_COMPASS_DRDY_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_COMPASS_DRDY_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_GYRO_INT_N_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_GYRO_INT_N_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_ACC_INT_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_ACC_INT_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_EXT_2V85_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_EXT_2V85_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);	
	gpio_cfg[GPIO_LCD_RESET_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_RESET_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_LCD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_LCD_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[GPIO_KEYPAD_LED_EN_INDEX] = 
		GPIO_CFG(gpio_num[GPIO_RED_LED_EN_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV0_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV0_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KYPD_DRV1_INDEX] = 
		GPIO_CFG(gpio_num[KYPD_DRV1_INDEX], 0, GPIO_CFG_OUTPUT, GPIO_CFG_NO_PULL, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N0_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N0_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
	gpio_cfg[KEYSENSE_N1_INDEX] = 
		GPIO_CFG(gpio_num[KEYSENSE_N1_INDEX], 0, GPIO_CFG_INPUT, GPIO_CFG_PULL_UP, GPIO_CFG_2MA);
}





